import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import NextUIProvider from "@/providers/next-ui-providers";
import SessionProvider from "@/providers/session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <NextUIProvider>
            <div className="container mx-auto px-4 max-w-6xl">
              <Header />
              {children}
            </div>
          </NextUIProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
